### ISSUE TITLE
请问群晖docker怎么修改

### ISSUE THREAD

**Issue by ShmilyStar** [imashen/docker-aio#1]
![QQ截图20240701224513](https://github.com/imashen/docker-aio/assets/92926599/98e62b44-edf6-483b-95dd-3023dd92a221)
我添加注册表后，刷新界面是空白的，看不到镜像列表

**Comment by imashen** [comment]
在你的注册表以此点击：设置👉选择官方存储库👉编辑👉启用注册表镜像👉填入 http://docker.13140521.xyz 👉勾选信任的SSL自我签署证书

**Comment by imashen** [comment]
### 打开 Docker 套件：
在主菜单中找到并打开 Docker 套件。
### 访问注册表设置：
打开 Docker 套件后，点击左侧的 注册表 标签。
### 添加新的镜像源：
在 注册表 页面中，点击右上角的 设置 按钮。
在弹出的窗口中，选择 镜像 标签。
在 镜像 标签下，点击 添加 按钮，输入新的镜像源 URL， http://docker.13140521.xyz
### 设置默认镜像源：
在镜像源列表中，找到刚刚添加的镜像源，点击其右侧的 三点 按钮，选择 设为默认。

**Comment by ShmilyStar** [comment]
> ### 打开 Docker 套件：
> 在主菜单中找到并打开 Docker 套件。
> 
> ### 访问注册表设置：
> 打开 Docker 套件后，点击左侧的 注册表 标签。
> 
> ### 添加新的镜像源：
> 在 注册表 页面中，点击右上角的 设置 按钮。 在弹出的窗口中，选择 镜像 标签。 在 镜像 标签下，点击 添加 按钮，输入新的镜像源 URL， http://docker.13140521.xyz
> 
> ### 设置默认镜像源：
> 在镜像源列表中，找到刚刚添加的镜像源，点击其右侧的 三点 按钮，选择 设为默认。

![QQ截图20240702000340](https://github.com/imashen/docker-aio/assets/92926599/fc1e6916-6349-4a2c-8bb3-4cb9b595a7cf)
不行啊，按这个添加地址后，注册表界面一片空白

**Comment by imashen** [comment]
就是选择官方的那个“Docker Hub”，点击编辑，然后里面有一个镜像选项，填入
