### ISSUE TITLE
请问linux上没有root权限的用户要怎么使用这个？

### ISSUE THREAD

**Issue by roki1031** [imashen/docker-aio#2]

**Comment by imashen** [comment]
只需要在每一条指令之前加入sudo就可以了
或者直接sudo -i提权切换到root用户运行亦可

**Comment by imashen** [comment]
我给的指令都是基于普通用户环境下的指令，并非提权的root用户，应该不会出问题

**Comment by imashen** [comment]
I will close this issue and reopen it if you still need help!
